// Code generated by MockGen. DO NOT EDIT.
// Source: category.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/Vladimir-Cha/product_accounting_service/internal/entities"
	gomock "github.com/golang/mock/gomock"
)

// MockCategoryStore is a mock of CategoryStore interface.
type MockCategoryStore struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryStoreMockRecorder
}

// MockCategoryStoreMockRecorder is the mock recorder for MockCategoryStore.
type MockCategoryStoreMockRecorder struct {
	mock *MockCategoryStore
}

// NewMockCategoryStore creates a new mock instance.
func NewMockCategoryStore(ctrl *gomock.Controller) *MockCategoryStore {
	mock := &MockCategoryStore{ctrl: ctrl}
	mock.recorder = &MockCategoryStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryStore) EXPECT() *MockCategoryStoreMockRecorder {
	return m.recorder
}

// CreateCat mocks base method.
func (m *MockCategoryStore) CreateCat(ctx context.Context, category *entities.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCat", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCat indicates an expected call of CreateCat.
func (mr *MockCategoryStoreMockRecorder) CreateCat(ctx, category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCat", reflect.TypeOf((*MockCategoryStore)(nil).CreateCat), ctx, category)
}

// DeleteCat mocks base method.
func (m *MockCategoryStore) DeleteCat(ctx context.Context, id int) (*entities.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCat", ctx, id)
	ret0, _ := ret[0].(*entities.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCat indicates an expected call of DeleteCat.
func (mr *MockCategoryStoreMockRecorder) DeleteCat(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCat", reflect.TypeOf((*MockCategoryStore)(nil).DeleteCat), ctx, id)
}

// ReadCat mocks base method.
func (m *MockCategoryStore) ReadCat(ctx context.Context, id int) (*entities.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCat", ctx, id)
	ret0, _ := ret[0].(*entities.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadCat indicates an expected call of ReadCat.
func (mr *MockCategoryStoreMockRecorder) ReadCat(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCat", reflect.TypeOf((*MockCategoryStore)(nil).ReadCat), ctx, id)
}

// UpdateCat mocks base method.
func (m *MockCategoryStore) UpdateCat(ctx context.Context, category *entities.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCat", ctx, category)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCat indicates an expected call of UpdateCat.
func (mr *MockCategoryStoreMockRecorder) UpdateCat(ctx, category interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCat", reflect.TypeOf((*MockCategoryStore)(nil).UpdateCat), ctx, category)
}
